[versions]
#编译环境
agp = "9.2.0"
compileSdkVersion = "37"
#最小版本Android 8.0 (API 26)
minSdkVersion = "26"
#noinspection OldTargetApi
targetSdkVersion = "36"
#依赖库版本
coreKtx = "1.18.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
google-android-material = { group = "com.google.android.material", name = "material", version = "1.13.0" }
google-jetpack-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.1" }
google-jetpack-activity = { group = "androidx.activity", name = "activity", version = "1.13.0" }
google-jetpack-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.2.1" }

#单元测试
junit = { group = "junit", name = "junit", version = "4.13.2" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version = "1.3.0" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.7.0" }



[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

